### ISSUE TITLE
Modal - boolean prop to reactive show or hide

### ISSUE THREAD

**Issue by melanke** [simplitech/simpli-web-sdk#13]

**Comment by ftgibran** [comment]
I strongly recommend doing the `$.modal.open` / `$.modal.close` instead. 
Doing by prop, it will only be used in the parent component (not globally).
However, if you really need it, I can include this feature in v2.x

**Comment by melanke** [comment]
Yeah, I need this feature, there is so many usecases for when I need a modal only for a specific view and using a prop is so much easier
I don´t think it will break compatibility with the 1.x, so there is no need to delay it
