### ISSUE TITLE
Resource with multiple endpoints and more explicit method names

### ISSUE THREAD

**Issue by melanke** [simplitech/simpli-web-sdk#4]
We should be able to declare multiple endpoints so we could create multple methods for retrieving and sending content (with orgnized url strings), and the current default methods aren't explicit enought, let´s discuss about them in this issue

**Comment by melanke** [comment]
Currently, To make a custom request that returns a collection we need to explicitly set a new endpoint in the constructor, like this: `new Collection<MyClass>("my/endpoint")` or worst: we need to inherit a Collection.

To make it easier, and to be able to organize all endpoint in the same location, I believe we should quit using the Model to make the request and use a helper class, something like this:
```typescript
const resp = new Collection<MyClass>()
const req = new MyReqClass()
const endpoint = MyClass.listEndpoint
await http.get(endpoint, req, resp)
```

**Comment by melanke** [comment]
It´s important to be able to specify wich fields do you want to send and receive for each endpoint, maybe an optional schema or array could be the solution

**Comment by ftgibran** [comment]
The Collection and Resouce class have methods that work with certain individual processes that facilitate the request and the response. By removing the request in them, the proposal of those classes are lost. Therefore, this functionality needs to remain on them. 

Currently, there are helpers (GET, POST, PUT, DELETE, call) or even the HttpBody class that can do what you have written. 

I can consider to implement `custom actions` like https://github.com/pagekit/vue-resource/blob/develop/docs/resource.md#custom-actions
This way, it is possible to configurate the Collection or Resource class to have other endpoints instead the main one.

**Comment by melanke** [comment]
Ok, I understand your concern, so we don't need to remove the http calls inside `Collection` and `Resource` but I think we should be able to make http calls without the need to instantiate an object like HttpBody, we should be able to call a static method, a helper function to do it. So Collection and Resource should use this helper function.

I think we are gona stop using vue-resource, so we can implement custom actions, in a different way, but it is a good idea.

**Comment by melanke** [comment]
This issue is blocked by #5

**Comment by melanke** [comment]
There is also another problem: I can't use "Find Usages" on the `find` method, so it's really hard to know who is using the endpoint

**Comment by ftgibran** [comment]
Please read [Resources and Requests](https://github.com/simplitech/simpli-web-sdk/blob/v2.x/docs/resources-and-requests.md) to clarify your issues.

**Comment by melanke** [comment]
Very good! I am very excited to use it.
