### ISSUE TITLE
Validation on the Schema object (or as a field prop)

### ISSUE THREAD

**Issue by melanke** [simplitech/simpli-web-sdk#6]
After fixing issue #2, puting the validation in the schema object will make it more flexible, sometimes we need different validations for the same input

**Comment by ftgibran** [comment]
It is acceptable. However, the other way (validation by model decorator) needs to be available as well in order the user be able to choose the best option for him.

**Comment by melanke** [comment]
Sure, but I think we should´t use this option on simpli-cli

**Comment by melanke** [comment]
Maybe we can use this validator
https://github.com/benhurott/jzor
