### ISSUE TITLE
no component should obligate the object to have $tag, it should be optional, we should be able to declare as the component prop

### ISSUE THREAD

**Issue by melanke** [simplitech/simpli-web-sdk#7]
for example, <input-select> expect the items to have $tag, but sometimes, would be more confortable to declare as a prop of the input-select

**Comment by ftgibran** [comment]
Currently, the only component that uses the $tag is the SelectInput. I can consider this prop in order to be more flexible.

**Comment by melanke** [comment]
Let´s put this on 1.x and make $tag optional
